# Generated by Django 3.0.8 on 2020-07-16 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Baby class', 'Baby class'), ('Class 1', 'class 1'), ('Class 2', 'class 2'), ('Class 3', 'class 3'), ('Class 4', 'class 4'), ('Class 5', 'class 5'), ('Class 6', 'class 6'), ('Class 7', 'class 7')], max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Records',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_fees', models.FloatField(default=1000000)),
                ('received_fees', models.FloatField()),
                ('Remaining_fees', models.FloatField()),
                ('completed', models.BooleanField(default=False)),
                ('publish_date', models.DateTimeField(auto_now_add=True)),
                ('classrooms', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='records.Classroom')),
                ('students', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='records.Student')),
            ],
        ),
    ]
