# Generated by Django 3.0.8 on 2020-07-21 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='records',
            name='phone',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='records',
            name='Remaining_fees',
            field=models.FloatField(blank=True),
        ),
    ]
