# Generated by Django 3.0.8 on 2020-07-22 07:03

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0002_auto_20200721_1725'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='records',
            name='phone',
        ),
        migrations.AddField(
            model_name='records',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None),
        ),
    ]
